OLED_ENABLE = yes
OLED_DRIVER = ssd1306
OLED_TRANSPORT = i2c
#LTO_ENABLE = yes

CONSOLE_ENABLE = yes
ANALOG_ENABLE = yes
POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = analog_joystick

MOUSEKEY_ENABLE = yes

WPM_ENABLE = yes
